spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: gateway-test
              uri: http://localhost:8083
              predicates:
                - Path=/gateway/**
            - id: security-auth
              uri: http://localhost:8084
              predicates:
                - Path=/api/auth/**
            - id: security-users
              uri: http://localhost:8084
              predicates:
                - Path=/api/users/**
            - id: user-service
              uri: http://localhost:8080
              predicates:
                - Path=/user-module/**
            - id: analyse-module
              uri: http://localhost:8082
              predicates:
                - Path=/analytics/**

server:
  port: 8083

security:
  service:
    url: http://localhost:8084